import type { Metadata } from "next";
import { Archivo, Inter} from "next/font/google";
import "./globals.css";

import localFont from "next/font/local";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const glory = localFont({
  src: "../fonts/GiveYouGlory.ttf",
  variable: "--font-glory",
  display: "swap",
});

const archivo = Archivo({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-archivo",
});


export const metadata: Metadata = {
  title: "Panda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}${glory.variable} ${archivo.variable} bg-white `}
      >
        {children}
      </body>
    </html>
  );
}
